# Generated by Django 3.1.3 on 2020-11-26 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0001_initial'),
        ('chemical_composition', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chemicalcomposition',
            old_name='name',
            new_name='percentage',
        ),
        migrations.RemoveField(
            model_name='chemicalcomposition',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='chemicalcomposition',
            name='price',
        ),
        migrations.AddField(
            model_name='chemicalcomposition',
            name='elements',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='elements.elements'),
        ),
    ]
