# Generated by Django 3.1.3 on 2020-11-26 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0001_initial'),
        ('chemical_composition', '0002_auto_20201126_0526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chemicalcomposition',
            name='id',
        ),
        migrations.AlterField(
            model_name='chemicalcomposition',
            name='commodity',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='commodity.commodity'),
        ),
    ]
