# Generated by Django 3.1.3 on 2020-11-26 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chemical_composition', '0003_auto_20201126_0528'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChemicalComposition',
        ),
    ]
