# Generated by Django 3.1.3 on 2020-11-26 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commodity', '0001_initial'),
        ('elements', '0001_initial'),
        ('chemical_composition', '0004_delete_chemicalcomposition'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChemicalComposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.CharField(blank=True, max_length=255, null=True)),
                ('commodity', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='commodity.commodity')),
                ('elements', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='elements.elements')),
            ],
            options={
                'verbose_name': 'Chemical Composition',
                'verbose_name_plural': 'Composition',
                'db_table': 'chemical_composition',
            },
        ),
    ]
