# Generated by Django 3.1.3 on 2020-11-27 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chemical_composition', '0005_chemicalcomposition'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChemicalComposition',
        ),
    ]
